# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erik Jonasson's Blog
email: ejonasson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Erik is a web developer, gamer, public policy wonk, and many other things.
  This blog serves as a repository of any thoughts I may have that are too long for tweets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erikjonasson.me" # the base hostname & protocol for your site
twitter_username: ehjonasson
github_username:  ejonasson
future: true
# Build settings
markdown: kramdown
